version: '3'
services:
  vpronginx:
    build:
      context: ../Docker-web
    image: doublej99/vpronginx
    container_name: vproweb
    ports:
      - "80:80"

  vproapp:
    build:
      context: ../Docker-app/multistage
    image: doublej99/vproapp
    container_name: vproapp
    ports:
      - "8080:8080"

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vprodb:
    build:
      context: ../Docker-db
    image: doublej99/vprdb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

volumes:
  vprodbdata: {}
